services:
  docron.server:
    image: ghcr.io/primez/docron:latest
    container_name: docron-ghcr
    user: root # only for development
    ports:
      - 8080:8080
    environment:
      - DOCKER_CONNECTION=unix:///var/run/docker.sock
      - DB=Data Source=/data/docron.db;
      - KEY_PATH=/data/keys
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/d/Temp/sqlite/:/data
    
